### ISSUE TITLE
Support Arrays in Payload Fields

### ISSUE THREAD

**Issue by dknepprath** [MasonM/wiremock-jwt-extension#2]
The JWT specification states that `aud` audience can be an array of strings: https://tools.ietf.org/html/rfc7519#section-4.1.3 

Has support for payload fields with arrays been considered? Any concerns about heading down this path?

I'm interested in contributing to this effort.

**Comment by MasonM** [comment]
Sorry for the delay! 

This is a good feature request, and updating the request matcher to allow arrays turned out to be easy, so I went ahead and entered a PR: https://github.com/MasonM/wiremock-jwt-extension/pull/3

Please take a look and let me know if that's what you're looking for.

I didn't update the stub mapping transformer because it's not used much, but you're free to enter a PR to do so.

**Comment by dknepprath** [comment]
I'm relatively new to WireMock and completely new to extensions. A couple augmentations come to mind as I was playing around with this branch. Is it conceivable that we could enable:

1) Ignore order of the array. Match on contents of array even if the order of elements is different
2) Maybe a little more complex; an "array contains" match. A request will match as long as the request contains any of the specified elements in the array.

Our teams have use cases in mind for both of these scenarios.

**Comment by MasonM** [comment]
Okay, I released the changes in https://github.com/MasonM/wiremock-jwt-extension/pull/3 as version 0.5.

The augmentations you mentioned are a good idea, but I can't think of an easy way to implement them. Leveraging Wiremock's `com.github.tomakehurst.wiremock.matching.EqualToJsonPattern` class is probably the easiest. You're free to enter a PR for that.
